[package]
name = "c3-lang-parser"
version = "0.1.0"
edition = "2018"

[dependencies]
quote = "1"
syn = { version = "1", features = ["full", "extra-traits"] }
proc-macro2 = "1"
c3-lang-linearization = { path = "./../c3-lang-linearization" }

[dev-dependencies]
pretty_assertions = "1.2"
